--- 
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_unified
output_dir: output
base_url: http://userprimary.net
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less',
                   'markdown', 'md', 'php', 'rb', 'sass', 'txt', 'xml' ]